version: '3'

vars:
  ROOT_DIR:
    sh: pwd
  DATE:
    sh: date "+%Y-%m-%d--%H_%M"
  # LibreLane git revision for use with Nix
  LIBRELANE_REVISION: 3.0.0.dev44
  # LibreLane remote origin
  LIBRELANE_REMOTE: librelane/librelane

tasks:
  regmap:
    desc: Generates the register map
    cmds:
      - uv run peakrdl html -o docs/html --title "Wedgetail" regmap/wedgetail_spi.rdl
      - uv run peakrdl markdown -o docs/regmap.md regmap/wedgetail_spi.rdl
      - uv run python scripts/peakrdl_verilog.py
      # - uv run peakrdl sv -o src/ regmap/wedgetail_spi.rdl
      # delete extraneous files
      - rm src/wedgetail_spi_tb.cpp src/wedgetail_spi_tb.sv src/wedgetail_spi_tb_wires_include.vh
      - rm src/wedgetail_spi_wrapper_tb.sv src/wedgetail_spi_port_map_include.vh src/wedgetail_spi_ports_include.vh
      - rm src/wedgetail_spi_wires_include.vh

  tapeout_docker:
    desc: Most similar to GitHub CI
    cmds:
      - uv run python ./tt/tt_tool.py --create-user-config
      - mkdir -p runs/wokwi
      - uv run librelane --dockerized --pdk ihp-sg13g2 --run-tag wokwi --force-run-dir runs/wokwi src/config_merged.json

  # fuck sake, this isn't working
  # tapeout_nix:
  #   desc: Actually useful
  #   cmds:
  #     - uv run python ./tt/tt_tool.py --create-user-config
  #     - nix run github:{{ .LIBRELANE_REMOTE }}/{{ .LIBRELANE_REVISION }} -- --pdk ihp-sg13g2 --run-tag wokwi --force-run-dir runs/wokwi src/config_merged.json

  regmap_host:
    desc: Hosts documentation for the regmap
    cmds:
      - cd docs/html; uv run python -m http.server

  install_ihp:
    desc: Installs the IHP PDK locally
    cmds:
      - uv run ciel enable --pdk-family ihp-sg13g2 /c4b8b4e5e7a05f375cca3815d51b3a37721fbf5c
    status:
      - test -f ~/.ciel/ciel/ihp-sg13g2/versions/c4b8b4e5e7a05f375cca3815d51b3a37721fbf5c/ihp-sg13g2/libs.tech/magic/ihp-sg13g2.magicrc
