// This file was autogenerated by PeakRDL-verilog
module wedgetail_spi_rf #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 2,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 8    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              resetn,  //! Default reset

    // Register SYS_CTRL

  /* verilator lint_off SELRANGE *//* verilator lint_on SELRANGE */
    output logic                     [ 7: 0] SYS_CTRL_RESET_q,              //! Current field value

    // Register ECHO1

  /* verilator lint_off SELRANGE *//* verilator lint_on SELRANGE */
    output logic                     [ 7: 0] ECHO1_DATA_q,              //! Current field value

    // Register ECHO2

  /* verilator lint_off SELRANGE *//* verilator lint_on SELRANGE */
    output logic                     [ 7: 0] ECHO2_DATA_q,              //! Current field value

    // Register ROSC_EN_SEL

  /* verilator lint_off SELRANGE *//* verilator lint_on SELRANGE */
    output logic                     [ 7: 0] ROSC_EN_SEL_DATA_q,              //! Current field value

    // Register Bus
    input  logic                             valid,    //! Active high valid
    input  logic                             read,     //! Indicates request is a read
    input  logic            [ADDR_WIDTH-1:0] addr,     //! Address (byte aligned, absolute address)
    /* verilator lint_off UNUSED */
    input  logic            [DATA_WIDTH-1:0] wdata,    //! Write data
    input  logic          [DATA_WIDTH/8-1:0] wmask,    //! Write mask
    /* verilator lint_on UNUSED */
    output logic            [DATA_WIDTH-1:0] rdata     //! Read data
);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [ 7: 0] SYS_CTRL_RESET_next;
    logic                             SYS_CTRL_RESET_anded;
    logic                             SYS_CTRL_RESET_ored;
    logic                             SYS_CTRL_RESET_xored;
    logic                           [ 7: 0] ECHO1_DATA_next;
    logic                             ECHO1_DATA_anded;
    logic                             ECHO1_DATA_ored;
    logic                             ECHO1_DATA_xored;
    logic                           [ 7: 0] ECHO2_DATA_next;
    logic                             ECHO2_DATA_anded;
    logic                             ECHO2_DATA_ored;
    logic                             ECHO2_DATA_xored;
    logic                           [ 7: 0] ROSC_EN_SEL_DATA_next;
    logic                             ROSC_EN_SEL_DATA_anded;
    logic                             ROSC_EN_SEL_DATA_ored;
    logic                             ROSC_EN_SEL_DATA_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    assign sw_wr    = valid && !read;
    assign sw_rd    = valid &&  read;
    assign sw_wdata = wdata;
    assign rdata    = sw_rdata;

    // convert byte mask to bit mask
    always_comb begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] SYS_CTRL_rdata;
    logic                     [DATA_WIDTH-1:0] ECHO1_rdata;
    logic                     [DATA_WIDTH-1:0] ECHO2_rdata;
    logic                     [DATA_WIDTH-1:0] ROSC_EN_SEL_rdata;

    assign sw_rdata = // or of each register return (masked)
                   SYS_CTRL_rdata | 
                   ECHO1_rdata | 
                   ECHO2_rdata | 
                   ROSC_EN_SEL_rdata;
            
        
    // ============================================================
    // Register: SYS_CTRL
    //    [ 7: 0]                RESET: hw=r     sw=w     reset=0x0
    // ============================================================
    logic                  SYS_CTRL_decode;
    logic                  SYS_CTRL_sw_wr;
    logic                  SYS_CTRL_sw_rd;
    logic [DATA_WIDTH-1:0] SYS_CTRL_q;

    assign SYS_CTRL_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign SYS_CTRL_sw_wr = sw_wr && SYS_CTRL_decode;
    assign SYS_CTRL_sw_rd = sw_rd && SYS_CTRL_decode;

    always_comb begin
        SYS_CTRL_q = '0;
        SYS_CTRL_q[ 7: 0] = SYS_CTRL_RESET_q;
    end

    // masked version of return data
    assign SYS_CTRL_rdata = SYS_CTRL_sw_rd ? SYS_CTRL_q : 'b0;

    // ------------------------------------------------------------
    // Field: RESET
    // ------------------------------------------------------------
    assign SYS_CTRL_RESET_anded = & SYS_CTRL_RESET_q;
    assign SYS_CTRL_RESET_ored  = | SYS_CTRL_RESET_q;
    assign SYS_CTRL_RESET_xored = ^ SYS_CTRL_RESET_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        SYS_CTRL_RESET_q <= 0;
    end else begin
        // Software write
        if (SYS_CTRL_sw_wr) begin
            SYS_CTRL_RESET_q <=  sw_masked_data[ 7: 0] | (SYS_CTRL_RESET_q & ~sw_mask[ 7: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ECHO1
    //    [ 7: 0]                 DATA: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  ECHO1_decode;
    logic                  ECHO1_sw_wr;
    logic                  ECHO1_sw_rd;
    logic [DATA_WIDTH-1:0] ECHO1_q;

    assign ECHO1_decode = (addr == (ADDR_OFFSET+'h0+'h1));
    assign ECHO1_sw_wr = sw_wr && ECHO1_decode;
    assign ECHO1_sw_rd = sw_rd && ECHO1_decode;

    always_comb begin
        ECHO1_q = '0;
        ECHO1_q[ 7: 0] = ECHO1_DATA_q;
    end

    // masked version of return data
    assign ECHO1_rdata = ECHO1_sw_rd ? ECHO1_q : 'b0;

    // ------------------------------------------------------------
    // Field: DATA
    // ------------------------------------------------------------
    assign ECHO1_DATA_anded = & ECHO1_DATA_q;
    assign ECHO1_DATA_ored  = | ECHO1_DATA_q;
    assign ECHO1_DATA_xored = ^ ECHO1_DATA_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        ECHO1_DATA_q <= 0;
    end else begin
        // Software write
        if (ECHO1_sw_wr) begin
            ECHO1_DATA_q <=  sw_masked_data[ 7: 0] | (ECHO1_DATA_q & ~sw_mask[ 7: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ECHO2
    //    [ 7: 0]                 DATA: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  ECHO2_decode;
    logic                  ECHO2_sw_wr;
    logic                  ECHO2_sw_rd;
    logic [DATA_WIDTH-1:0] ECHO2_q;

    assign ECHO2_decode = (addr == (ADDR_OFFSET+'h0+'h2));
    assign ECHO2_sw_wr = sw_wr && ECHO2_decode;
    assign ECHO2_sw_rd = sw_rd && ECHO2_decode;

    always_comb begin
        ECHO2_q = '0;
        ECHO2_q[ 7: 0] = ECHO2_DATA_q;
    end

    // masked version of return data
    assign ECHO2_rdata = ECHO2_sw_rd ? ECHO2_q : 'b0;

    // ------------------------------------------------------------
    // Field: DATA
    // ------------------------------------------------------------
    assign ECHO2_DATA_anded = & ECHO2_DATA_q;
    assign ECHO2_DATA_ored  = | ECHO2_DATA_q;
    assign ECHO2_DATA_xored = ^ ECHO2_DATA_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        ECHO2_DATA_q <= 0;
    end else begin
        // Software write
        if (ECHO2_sw_wr) begin
            ECHO2_DATA_q <=  sw_masked_data[ 7: 0] | (ECHO2_DATA_q & ~sw_mask[ 7: 0]);
        end
    end
            
        
    // ============================================================
    // Register: ROSC_EN_SEL
    //    [ 7: 0]                 DATA: hw=r     sw=rw    reset=0x0
    // ============================================================
    logic                  ROSC_EN_SEL_decode;
    logic                  ROSC_EN_SEL_sw_wr;
    logic                  ROSC_EN_SEL_sw_rd;
    logic [DATA_WIDTH-1:0] ROSC_EN_SEL_q;

    assign ROSC_EN_SEL_decode = (addr == (ADDR_OFFSET+'h0+'h3));
    assign ROSC_EN_SEL_sw_wr = sw_wr && ROSC_EN_SEL_decode;
    assign ROSC_EN_SEL_sw_rd = sw_rd && ROSC_EN_SEL_decode;

    always_comb begin
        ROSC_EN_SEL_q = '0;
        ROSC_EN_SEL_q[ 7: 0] = ROSC_EN_SEL_DATA_q;
    end

    // masked version of return data
    assign ROSC_EN_SEL_rdata = ROSC_EN_SEL_sw_rd ? ROSC_EN_SEL_q : 'b0;

    // ------------------------------------------------------------
    // Field: DATA
    // ------------------------------------------------------------
    assign ROSC_EN_SEL_DATA_anded = & ROSC_EN_SEL_DATA_q;
    assign ROSC_EN_SEL_DATA_ored  = | ROSC_EN_SEL_DATA_q;
    assign ROSC_EN_SEL_DATA_xored = ^ ROSC_EN_SEL_DATA_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        ROSC_EN_SEL_DATA_q <= 0;
    end else begin
        // Software write
        if (ROSC_EN_SEL_sw_wr) begin
            ROSC_EN_SEL_DATA_q <=  sw_masked_data[ 7: 0] | (ROSC_EN_SEL_DATA_q & ~sw_mask[ 7: 0]);
        end
    end

endmodule: wedgetail_spi_rf
